.TH ZZZRUN "8" "July 14, 2017" "zzzrun.sh" "System Administration Commands"
.SH NAME
zzzrun \- run command if ZFS pool has no sleeping hard drives
.ds p zzzrun
.ds t @zzzrun-pool
.SH SYNOPSIS
.B \*p
[\fIoptions\fR]
[\fB-p\fR \fIPOOL\fR] ...
\fICOMMAND\fR [\fB\*t\fR] ...
.SH DESCRIPTION
.B \*p
checks the standby/sleep status of all rotational drives in a ZFS pool
(using \fBhdparm -C\fR), and only if they are all active/idle runs the
command supplied.
Use this utility to avoid spinning up drives unnecessarily.
.SH OPTIONS
.TP
.B \-s
Single run.  By default \fB\*p\fR will check and execute on a per pool
basis.
This option will instead check all disks across all pools in scope and
execute \fICOMMAND\fR just once if there are no disks in standby/sleep.
.TP
.B \-v
Verbose mode.  Report warnings and information.  By default this
utility will only report errors.
.TP
.B \-vv
Very verbose.  Report debugging messages.
.TP
.B \-p\fR \fIPOOL
Specify a pool to check, otherwise all available pools are included by
default.
Repeat this option to specify more than one pool.
Any pools specified that are unavailable will be ignored.
A warning is given if none of the pools are available.
.TP
.I COMMAND
Command to execute if no hard drives in the pool(s) are in standby or
sleep modes.
.IP
Optionally, use the token \fB\*t\fR one or more times in the command's
arguments to have \fB\*p\fR insert the pool scope when running the
command.
If using \fB\*p -s\fR this will be a list of all available specified
pools, otherwise this will be the name of each pool as \fB\*p\fR
iterates through them.
.SH EXAMPLES
To use
.BR zfs-auto-snapshot (8)
without waking up any sleeping hard drives:
.PP
.nf
.RS
\*p zfs-auto-snapshot -qg -lfrequent -k4 \*t
.RE
.fi
.PP
.SH LIMITATIONS
Some drives do not report their power state correctly (particularly if
they are connected via USB) so in those cases this utility will either
permit command execution on sleeping/standby drives, or fail to run the 
command for an otherwise fully active pool.  Where \fBhdparm -C\fR
returns "unknown" for a drive, \fB\*p\fR will interpret this as
active/idle.
.SH SEE ALSO
.BR zfs (8),
.BR hdparm (8),
.BR zfs-auto-snapshot (8)
